image:
  file: .gitpod.Dockerfile
tasks:
  - name: Dependencies
    init: |
      npm ci
      npx playwright install
    command: export SANDBOX_URL="$(gp url 8080 2>/dev/null)" && npm ci && npm start
ports:
  - port: 8080
